"""公招结果图片渲染模块

使用 nonebot-plugin-htmlkit 将公招组合计算结果渲染为图片
本地预览：python fio_bot/plugins/mrfz/render.py
"""

from __future__ import annotations

# rarity_display 在运行时延迟导入，避免循环 / NoneBot 依赖问题
_rarity_display = None


def _get_rarity_display(rarity: int) -> str:
    """获取星级显示文本，兼容独立运行"""
    global _rarity_display
    if _rarity_display is None:
        try:
            from .recruit import rarity_display
            _rarity_display = rarity_display
        except ImportError:
            # 独立运行时的回退实现
            _stars = {0: "★", 1: "★★", 2: "★★★", 3: "★★★★", 4: "★★★★★", 5: "★★★★★★"}
            _rarity_display = lambda r: _stars.get(r, f"{r + 1}★")
    return _rarity_display(rarity)


# ==================== 颜色配置 ====================

# 稀有度颜色（0-based, CSS hex）
RARITY_COLORS: dict[int, str] = {
    0: "#969696",   # 1★ 灰色
    1: "#c8c8c8",   # 2★ 白色
    2: "#64b4ff",   # 3★ 蓝色
    3: "#c896ff",   # 4★ 紫色
    4: "#ffc83c",   # 5★ 金色
    5: "#ff7832",   # 6★ 橙色
}

# 保底星级高亮色（1-based）
MIN_STAR_COLORS: dict[int, str] = {
    1: "#969696",
    4: "#c896ff",
    5: "#ffc83c",
    6: "#ff7832",
}

# ==================== CSS 样式 ====================

_CSS = """\
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    background: #1e1e23;
    color: #f0f0f0;
    font-family: "Noto Sans SC", "Microsoft YaHei", sans-serif;
    padding: 28px 28px 20px;
    width: 520px;
}
.title {
    font-size: 22px;
    font-weight: bold;
    color: #ffc850;
    margin-bottom: 8px;
}
.tags-info {
    font-size: 16px;
    color: #aaaab4;
    margin-bottom: 14px;
}
.empty-hint {
    font-size: 15px;
    color: #aaaab4;
    padding: 10px 0;
}
.card {
    background: #2d2d34;
    border: 1px solid #464650;
    border-radius: 8px;
    margin-bottom: 10px;
    padding: 14px 16px;
    border-left: 4px solid #64b4ff;
}
.card-header {
    width: 100%;
    margin-bottom: 8px;
}
.card-header td {
    vertical-align: middle;
}
.card-title {
    font-size: 16px;
    font-weight: bold;
    color: #f0f0f0;
}
.card-badge {
    font-size: 13px;
    font-weight: bold;
    text-align: right;
}
.op-row {
    font-size: 15px;
    padding: 2px 0;
}
.footer {
    text-align: center;
    font-size: 12px;
    color: #64646e;
    margin-top: 6px;
}
"""


# ==================== 渲染 ====================


def _build_html(tags: list[str], results: list[dict]) -> str:
    """构建公招结果的 HTML"""
    parts: list[str] = []
    parts.append(f"<html><head><style>{_CSS}</style></head><body>")

    # 标题
    parts.append('<div class="title">明日方舟公招分析</div>')

    # 识别标签
    tag_text = "、".join(tags)
    parts.append(f'<div class="tags-info">识别标签：{tag_text}</div>')

    # 空结果
    if not results:
        parts.append('<div class="empty-hint">没有找到有价值的标签组合</div>')
        parts.append("</body></html>")
        return "".join(parts)

    # 组合卡片
    for r in results:
        min_star = r["min_rarity"] + 1
        tag_str = " + ".join(r["tags"])
        bar_color = MIN_STAR_COLORS.get(min_star, "#64b4ff")
        badge_color = MIN_STAR_COLORS.get(min_star, "#f0f0f0")

        parts.append(f'<div class="card" style="border-left-color:{bar_color};">')

        # 卡片头：标签组合（左）+ 保底星级（右），用 table 实现两端对齐
        parts.append('<table class="card-header"><tr>')
        parts.append(f'<td><span class="card-title">【{tag_str}】</span></td>')
        parts.append(
            f'<td class="card-badge" style="color:{badge_color};">保底{min_star}★</td>'
        )
        parts.append("</tr></table>")

        # 干员列表
        for op in r["operators"]:
            rarity = op["rarity"]
            color = RARITY_COLORS.get(rarity, "#f0f0f0")
            star_text = _get_rarity_display(rarity)
            name = op["name"]
            parts.append(
                f'<div class="op-row" style="color:{color};">'
                f"{star_text} {name}</div>"
            )

        parts.append("</div>")

    # 底部签名
    parts.append('<div class="footer">Generated by @fiobot</div>')
    parts.append("</body></html>")

    return "".join(parts)


async def render_recruit_result(tags: list[str], results: list[dict]) -> bytes:
    """
    将公招结果渲染为图片

    Args:
        tags: 用户识别到的标签列表
        results: find_recruit_combinations 的返回值

    Returns:
        PNG 图片的 bytes
    """
    from nonebot import require

    require("nonebot_plugin_htmlkit")
    from nonebot_plugin_htmlkit import html_to_pic

    html = _build_html(tags, results)
    return await html_to_pic(html=html, max_width=520)


# ==================== 本地预览 ====================

def _preview():
    """生成示例 HTML 并在浏览器中打开，用于本地调试样式"""
    import tempfile
    import webbrowser

    # 模拟数据
    sample_tags = ["高级资深干员", "近卫干员", "输出"]
    sample_results = [
        {
            "tags": ["高级资深干员", "近卫干员"],
            "min_rarity": 5,
            "operators": [
                {"name": "银灰", "rarity": 5},
                {"name": "棘刺", "rarity": 5},
                {"name": "耀骑士临光", "rarity": 5},
            ],
        },
        {
            "tags": ["近卫干员", "输出"],
            "min_rarity": 3,
            "operators": [
                {"name": "银灰", "rarity": 5},
                {"name": "棘刺", "rarity": 5},
                {"name": "星熊", "rarity": 4},
                {"name": "杜宾", "rarity": 3},
                {"name": "艾丝黛尔", "rarity": 2},
            ],
        },
        {
            "tags": ["输出"],
            "min_rarity": 3,
            "operators": [
                {"name": "能天使", "rarity": 5},
                {"name": "陨星", "rarity": 4},
                {"name": "白雪", "rarity": 3},
            ],
        },
    ]

    html = _build_html(sample_tags, sample_results)

    with tempfile.NamedTemporaryFile("w", suffix=".html", delete=False, encoding="utf-8") as f:
        f.write(html)
        path = f.name

    webbrowser.open(path)
    print(f"已在浏览器中打开预览：{path}")


if __name__ == "__main__":
    _preview()
